import type { NewsCopy } from "@/components/b2b/fox-news-copy";

export const enNews: Record<string, NewsCopy> = {
  "face-wash-fox-hanh-trinh-tu-y-tuong-den-thuong-hieu-tien-phong": {
    title: "Face Wash Fox — from an idea to a tech skincare brand",
    excerpt:
      "Vietnam’s first tech facial chain in major malls, opening a high-potential niche.",
    intro:
      "As technology reaches every part of daily life, beauty is going through the same shift.",
    lead: "One bright spot in Vietnam is Face Wash Fox — a tech facial chain in major shopping malls, opening a high-potential niche.",
    cta: "Source: Tienphong.vn",
    texts: [
      "From a small idea to a bigger move",
      'It started with a question: "How do we stop treating face washing as the overlooked step in skincare?" The founders of Face Wash Fox brought a modern answer — tech facial cleansing. Instead of a traditional wash, guests get a deep-clean treatment combining premium Hydra Facial technology with specialized dermocosmetics.',
      "A modern space, a professional process, and results you can see in 30–40 minutes — that is why guests come back, especially in a society that values speed, convenience, and real results.",
      "Shaping a tech facial ecosystem",
      "In a short time, Face Wash Fox expanded across Ho Chi Minh City, Hanoi, and Nha Trang. Appearing in flagship malls such as Saigon Centre, Landmark 81, Aeon Mall, and Crescent Mall, the brand quickly drew young people and office workers who want skincare but have little time.",
      'More than a "face-wash shop", Face Wash Fox built a facial washing bar — a place for thorough consultation, modern machines, and a relaxing skincare space at an accessible price.',
      "A long view and a real difference",
      "Amid a boom of beauty models, Face Wash Fox stands out through serious operations: a standardized process across the system, well-trained technicians, products with clear origins, and service that keeps evolving.",
      "According to the brand, Face Wash Fox will keep upgrading technology, developing deeper personalized treatments, offering AI skin consultation, and expanding nationwide.",
      "Connecting technology with a modern lifestyle",
      "Face Wash Fox is not just skincare — it positions itself as part of a lifestyle, where anyone can care for themselves quickly, effectively, and with care. That is why it is seen as a pioneer of tech facial cleansing in Vietnam.",
      "Face Wash Fox — from a bold idea to a leading brand — shows that when technology meets a real need, it can make a breakthrough on Vietnam’s beauty map.",
    ],
    alts: [
      "After coffee, car washes, and haircuts, Vietnam has its first facial-cleansing chain",
      "Face Wash Fox brings professional facial cleansing and skincare technology to Vietnam",
      "Face Wash Fox stores are designed to feel fresh and energetic",
      "Guests receive consultation from technicians at Face Wash Fox",
    ],
  },
  "tiktoker-anh-mat-vuong-tro-thanh-dai-su-thuong-hieu-cua-face-wash-fox": {
    title: 'TikToker “Anh Mặt Vuông” becomes Face Wash Fox brand ambassador',
    excerpt:
      "Not a perfect face, and not flawless skin — that is exactly why Face Wash Fox chose TikToker “Anh Mặt Vuông” as brand ambassador for 2026.",
    intro: "Not a perfect face, and not flawless skin.",
    lead: "That is exactly why Face Wash Fox chose TikToker “Anh Mặt Vuông” as brand ambassador for 2026.",
    cta: "Source: Dantri.com.vn — Consultation hotline: 08898 66666",
    texts: [
      'Duong Minh Tan, born in 1999 and known to millions as "Anh Mặt Vuông", is now the face of the Face Wash Fox skincare chain this year.',
      "This is not the first time a TikToker has partnered with a beauty brand, but it is the first time Face Wash Fox has chosen a creator to tell its story.",
      "A real person, a real story",
      "From a car-selling channel to a creator with more than 1.1 million followers and 46.8 million likes on TikTok, Duong Minh Tan’s path never followed a formula.",
      "He rose not because of a textbook look, but because he felt so real that viewers saw themselves in his videos. That is also what Face Wash Fox was looking for.",
      '"We did not want a perfect face to advertise skincare. We wanted a real person — someone who knows skincare is not just for some people, and who is not afraid to say that to millions of viewers," a Face Wash Fox representative said.',
      "Men and skincare — no longer a distant story",
      '"Anh Mặt Vuông" is not the first person to break the idea that "guys do not need skincare". But with an audience that is mostly Gen Z and Millennials — generations more open to taking care of themselves — he can tell that story naturally.',
      "Before becoming ambassador, Duong Minh Tan experienced a full Face Wash Fox routine for the first time: AI skin analysis, a clear read of his real skin, and care personalized to his skin type. His reaction after that visit was why Face Wash Fox decided it did not need to look further.",
      '"It was the first time I really understood what my skin needed — not generic advice, but something exact. I did not think skincare could be this simple and this real," Duong Minh Tan said.',
      "The journey ahead",
      "As brand ambassador for 2026, “Anh Mặt Vuông” will join Face Wash Fox in communications, creative content, and experience events the same way he does everything: honest, close, and without a forced image.",
      "Face Wash Fox now has nearly 50 stores nationwide, with an AI skin-scan process that personalizes each visit — regardless of gender or skin type. Scan results are for reference and do not replace medical diagnosis.",
      "And that may be the common ground: both Face Wash Fox and “Anh Mặt Vuông” believe what is real is worth keeping for the long run.",
    ],
    alts: [
      "Face Wash Fox brand ambassador 2026 — “Anh Mặt Vuông”",
      "Signing ceremony announcing “Anh Mặt Vuông” as Face Wash Fox brand ambassador 2026",
      "Face Wash Fox high-tech facial chain",
      "Face Wash Fox brand ambassador 2026 — “Anh Mặt Vuông”",
    ],
  },
  "face-wash-fox-va-hanh-trinh-kien-tao-van-hoa-doanh-nghiep": {
    title:
      "Face Wash Fox and the making of a company culture: care, quality, and modernity",
    excerpt:
      "More than a tech facial brand, Face Wash Fox builds its place through company culture.",
    intro: "More than a brand in the tech facial model.",
    lead: "Face Wash Fox is earning its place through company culture — where service quality, a dedicated team, and a modern way of working come together for sustainable growth.",
    cta: "Source: Laodong.vn",
    texts: [
      "People at the center",
      'Known as a tech facial chain in Vietnam, few people see that behind the modern "facial washing bar" is a team of well-trained technicians who keep updating technology and skill. At Face Wash Fox, every staff member is a "brand ambassador" — carrying care to guests through a professional attitude and precise technique.',
      '"We do not only hire for skill. More important is someone who cares about the work," a company representative said. That philosophy is the foundation of a stable, deep team.',
      "Guests at the center of every process",
      "Beyond modern skincare, Face Wash Fox focuses on personalizing the visit. Every guest is consulted carefully, with skin condition identified and a suitable treatment designed — something rare in high-speed beauty models.",
      "Notably, even with a presence in nearly 40 locations nationwide — from Ho Chi Minh City, Hanoi, Da Nang, Nha Trang, and Vung Tau — the system stays consistent in service quality and hospitality, from technicians to store managers.",
      "Building a modern, connected work culture",
      "At Face Wash Fox, culture is not a slogan. It shows in small actions: the welcome, precise machine operation, and support for one another on every shift. The workplace values professionalism without rigidity, giving people room to grow and stay for the long term.",
      "The mix of technology, skill, and attentive care is why the brand has a firm place with guests — especially young people, office workers, and middle-aged guests who enjoy looking after their skin.",
      'Helping shape "light aesthetics" in Vietnam',
      "More than a beauty service, Face Wash Fox aims to build a healthy, modern lifestyle, where anyone can care for themselves in a scientific way — saving time without losing results.",
      "With nearly 100,000 guests who have trusted the service, Face Wash Fox is helping change traditional skincare thinking and opening a new path for light aesthetics in Vietnam — a model that combines technology, health, and lasting beauty.",
      "Face Wash Fox is not simply a facial brand. It is becoming a symbol of a new beauty generation — smart, scientific, and human.",
    ],
    alts: [
      "Technicians at Face Wash Fox",
      "Guests experiencing services at Face Wash Fox",
      "The Face Wash Fox team",
    ],
  },
  "anh-mat-vuong-tung-khong-nghi-co-mot-ngay-minh-noi-ve-cham-da": {
    title: "Anh Mặt Vuông never thought he would talk about skincare",
    excerpt: "Not the first brand to come to him. But the brand he chose to stay with.",
    intro: "Not the first brand to come to him.",
    lead: "But the brand he chose to stay with.",
    cta: "Source: Vtv.vn — Consultation hotline: 08898 66666",
    texts: [
      "After more than 1.1 million followers and nearly 100 brand collaborations, Duong Minh Tan does not lack invitations. He chooses carefully — not because he is picky, but because he knows his audience sees through anything that is not real.",
      '"I make content based on honesty. If I do not really use it, do not really like it — the audience knows right away. And I do not want to trade that away."',
      "Face Wash Fox was not a brand he was introduced to and tried for the first time when he signed. He was already a guest — coming regularly, knowing the process, knowing what he needed each visit. When FWF offered an official partnership, his answer did not take long.",
      '"I am talking about something I already do and already like. Now I am just saying it louder."',
      "Why skincare — and why now",
      "Duong Minh Tan does not claim to be a skincare expert. He does not have a 10-step routine, does not track every ingredient, and is not a beauty enthusiast in the usual sense.",
      "He simply realized skincare was not as complicated as he thought. And when done the right way, the result is something he can see every day.",
      '"I think a lot of guys are like me — it is not that we do not want to care for our skin, we just do not know where to start. FWF felt comfortable from the beginning — no judgment, no complexity, no hard upsell. Let the machine tell the truth about the skin, then follow that."',
      "A storyteller’s view",
      "After more than three years making content, Duong Minh Tan knows one thing clearly: the best story is the one the storyteller actually lives in.",
      "As Face Wash Fox ambassador for 2026, he has no plan to tell the story differently. Still everyday observation. Still situations where viewers see themselves. Only this time, the story happens on a treatment bed, between the busy days of a creator who never stops running.",
      '"I do not become someone else as FWF ambassador. I am still Anh Mặt Vuông — only now this square face is looked after a little better," he said with a laugh.',
      "And that is why he said yes. Not because he was invited. Not because of a number. But because this is what he is already doing — and he sees no reason not to tell more than a million people the truth about it.",
      "Face Wash Fox and Anh Mặt Vuông — two things that seem unrelated. But both are built on the same thing: honesty that needs no explanation.",
    ],
    alts: [
      "Anh Mặt Vuông at Face Wash Fox",
      "Anh Mặt Vuông with Face Wash Fox",
      "Anh Mặt Vuông experiencing skincare at Face Wash Fox",
      "Face Wash Fox tech facial chain",
      "Face Wash Fox tech facial chain",
    ],
  },
  "nhung-bac-thang-tao-nen-ky-tich-doi-ngu-sang-lap-face-wash-fox": {
    title: "The steps behind the story: the Face Wash Fox founding team",
    excerpt:
      "The Face Wash Fox founders did not only build a beauty brand. They laid the ground for high-tech facial cleansing that still feels close to everyone.",
    intro: "Behind every major brand is a story of people who dared to think and dared to act.",
    lead: "The Face Wash Fox founding team did not only build a beauty brand. They laid the ground for a new approach: high-tech facial cleansing that is modern, yet close to everyone.",
    cta: "Source: Thanhnien.vn",
    texts: [
      "From a simple idea to a brand with scale",
      'It began with a simple but ambitious question: "How do we turn face washing into an essential habit that anyone can reach?" From that idea, the Face Wash Fox founders built a distinctive skincare system, where modern technology meets the art of looking after skin.',
      "The Face Wash Fox journey has been marked by steady steps: careful market research, developing the facial washing bar model in Vietnam, and constant improvement to give guests a quality experience. Each new store is a milestone, showing the brand’s growth in high-tech beauty.",
      "A vision to bring technology closer to everyone",
      "The Face Wash Fox founders — young, driven, and creative — keep one goal in view: bring beauty technology closer to each guest. Learning from global trends, they invested strongly in modern devices such as Hydra Facial, helping skin not only look clean but also feel nourished from within.",
      "Guests at Face Wash Fox do not only experience advanced technology. They also feel care in every service. Images of professional, attentive technicians beside modern devices have become the brand’s mark, creating a tech-beauty style of its own.",
      "Value from creative leadership",
      "Face Wash Fox does not stop at high-tech beauty processes. It also brings new value to Vietnam’s beauty industry. With a people-first philosophy, the founders built personalized services that walk with guests on a modern skincare journey.",
      'The Face Wash Fox message "Beautiful skin starts with cleansing" is not only a promise. It is a new standard the brand is working to shape. At key events, Face Wash Fox welcomes guests with professionalism and creativity, leaving a strong impression and a clear place in people’s minds.',
      "Writing the next chapter of modern beauty",
      "With a strategic view and a spirit of constant renewal, the Face Wash Fox founding team is writing a new chapter for high-tech beauty in Vietnam. Beyond practical value for guests, the brand is becoming an inspiration for positive change, helping raise the domestic beauty industry.",
    ],
    alts: [
      "A Face Wash Fox store",
      "A relaxing space",
      "Guests cared for with modern technology at Face Wash Fox",
      "Guests receive consultation and experience a Face Wash Fox treatment",
      "Face Wash Fox with modern beauty technology",
    ],
  },
  "mot-ngay-cua-anh-mat-vuong-tai-face-wash-fox-hau-truong": {
    title:
      "A day with “Anh Mặt Vuông” at Face Wash Fox — the backstage story no one expected him to tell",
    excerpt:
      "Few people know that between packed shoot days, Duong Minh Tan is often at Face Wash Fox. Not a trial visit — a habit from before he became ambassador.",
    intro: "A guest first — an ambassador later.",
    lead: "In March 2026, Face Wash Fox officially announced Duong Minh Tan — TikToker “Anh Mặt Vuông”, with more than 1.1 million followers — as brand ambassador for the year.",
    cta: "Source: Laodong.vn",
    texts: [
      "For the people involved, this was not the start of a relationship — it was official recognition of something that was already there.",
      "He came to Face Wash Fox because he liked it — and stayed because he saw real results.",
      '"I was a Face Wash Fox guest before I was an ambassador. My skin improved a lot," he said plainly.',
      "That is also why Face Wash Fox chose him. Not finding a fitting face and then convincing them to try. But realizing the person they needed was already there — walking into the store on his own, with no invitation.",
      '"We wanted someone who truly believes in what they are saying, and Anh Mặt Vuông is that person," a Face Wash Fox representative said about the partnership.',
      "A fast process — with real results",
      "Creators do not have much time. Shoots, meetings, travel — a long skincare session is something Duong Minh Tan cannot allow on a workday.",
      "That is exactly what he found at Face Wash Fox.",
      "Every visit starts with an AI skin scan — analyzing oil, hydration, and skin surface. Results are for reference and do not replace medical diagnosis. It only takes a few minutes, then the process is personalized from that result.",
      "Next come high-tech treatment steps — deep cleansing, extracting congestion, delivering actives with sonic waves, and locking in moisture with cold electrophoresis. Each step targets the issue the skin actually has — nothing extra, nothing skipped.",
      '"When I take care of my skin regularly at Face Wash Fox, my face changes a lot without taking much time. That is what I need," Anh Mặt Vuông said.',
      "What the camera cannot say — but the skin shows clearly",
      "Making video content means his face appears in front of millions of people every week. Under studio lights, after late nights, between a nonstop schedule — skin reflects everything the body is going through.",
      "Face Wash Fox does not promise magic. But with the right process, done regularly and personalized — the result is something he sees in the mirror each morning, with no one needing to say it.",
      '"Better skin means more confidence. And more confidence makes everything better — including standing in front of a camera," he said.',
      "As ambassador for 2026, Anh Mặt Vuông will join Face Wash Fox in communications and creative content — the same way he does everything: honestly, with no extra explanation needed.",
    ],
    alts: [
      "Signing ceremony announcing the Face Wash Fox brand ambassador 2026",
      "Tech skincare process at Face Wash Fox",
      "Anh Mặt Vuông experiencing skincare at Face Wash Fox",
    ],
  },
  "bi-mat-bieu-tuong-logo-face-wash-fox": {
    title: '"The symbol’s secret": the Face Wash Fox logo and the journey to guests’ hearts',
    excerpt:
      "The smart fox Foxie is the soul of Face Wash Fox identity — sharp, agile, and adaptable.",
    intro: "A logo — a story that is not only about design.",
    lead: 'The smart, quick fox known as "Foxie" is the soul of Face Wash Fox brand identity.',
    cta: "Source: Vtv.vn",
    texts: [
      "Why a fox? Because it stands for sharpness, skill, and adaptability — the values the brand wants to bring to every guest.",
      "From the website, store signs, and staff uniforms to product packaging, Foxie appears at every brand touchpoint — like a companion on each guest’s skincare journey.",
      "Identity is not only to be seen — it is to be remembered and trusted",
      'Every Face Wash Fox store uses bright, modern colors — easy to recognize, and warm to step into. The identity system was also built carefully to carry a clear message: "Beautiful skin starts with cleansing".',
      "Foxie is not only a mascot. It is the brand face that has inspired dozens of campaigns, helping guests remember and connect more deeply.",
      "From a symbol to a trend",
      "Beyond visual identity, Face Wash Fox has become a social phenomenon, with tech-facial experience videos reaching tens of millions of views on TikTok and Facebook. The hashtags #RuamatCongNghe and #FaceWashFox have drawn thousands of comments and shares, showing the reach of a brand with character.",
      "Face Wash Fox now has nearly 40 locations nationwide, serving nearly 100,000 guests, with a goal of 100 stores in 2025 — a determined ambition for a rising “light aesthetics” model.",
      "Connecting emotion from the smallest things",
      "When a brand can make a guest smile with just a logo, that is not only a visual win — it is a win in reaching emotion. Face Wash Fox is doing that with a simple but powerful symbol: Foxie the fox — playful, dedicated, and always walking with your skin.",
    ],
    alts: [
      "The fox that represents Face Wash Fox",
      "A Face Wash Fox store space",
      "Mascot Foxie represents the Face Wash Fox brand.",
      "Face Wash Fox on media platforms",
      "The Face Wash Fox store network nationwide",
    ],
  },
  "nam-gioi-viet-cham-soc-da-dep-trai-khong-phai-chuyen-ngai-ngung": {
    title: 'Vietnamese men and skincare — looking good is nothing to hide',
    excerpt:
      "A few years ago, a man walking into a skincare shop still drew strange looks. In 2026, that is no longer true.",
    intro: "A few years ago, a man walking into a skincare shop still drew strange looks.",
    lead: "In 2026, that is no longer true.",
    cta: "Source: Cafef.vn — Consultation hotline: 08898 66666",
    texts: [
      "At major skincare chains in Vietnam, the share of male guests has risen year after year. Not because of an imported trend — but because a new generation of men is starting to see that taking care of yourself is not only for women.",
      "Anh Mặt Vuông — TikToker Duong Minh Tan, 26, with more than 1.1 million followers — is one of the faces telling that story.",
      "A new generation of men: confident, and able to take care of themselves",
      "Gen Z and Millennials are redefining many things — including how men see self-care. It is no longer something to hide, and no longer “weird for a guy to do that.”",
      "Duong Minh Tan is the most natural face of that generation. He does not force a glossy image. No filter. He is not afraid to let the audience see his face — the square face famous across TikTok — as it is.",
      "And that is why, when he talks about skincare, people believe him.",
      '"I am not someone with perfect skin. But I am a real person — and I think that is what the audience needs to hear more than an ad face," Duong Minh Tan said.',
      "Face Wash Fox and a view with no divide",
      "When Face Wash Fox chose Anh Mặt Vuông as brand ambassador for 2026, it was not only a marketing decision. It was a statement — that skincare is for everyone, regardless of gender, age, or starting point.",
      "Across nearly 50 stores nationwide, Face Wash Fox serves guests from students and office workers to older family members coming in for the first time because their children invited them. The AI skin scan personalizes each person — no one-size formula, no mass approach. Scan results are for reference and do not replace medical diagnosis. Technology supports the rest of a fast process.",
      "That is also how Anh Mặt Vuông makes content — noticing small everyday details, finding what viewers see in themselves, then telling it in his own way.",
      "The self-care trend among Vietnamese men did not come from one campaign or one influencer. It came from a quiet change in how a generation sees itself — that looking better, feeling better, and feeling more confident is not anyone’s privilege.",
      "Anh Mặt Vuông is not the first to say this. But with more than a million people listening every day — he may be the one saying it loudest.",
    ],
    alts: [
      "Anh Mặt Vuông — face of the Face Wash Fox brand",
      "Anh Mặt Vuông — face of the Face Wash Fox brand",
      "Face Wash Fox serves guests of every gender",
      "Skincare does not need a special reason",
    ],
  },
  "face-wash-fox-tien-phong-trong-linh-vuc-cham-soc-da-cong-nghe-cao": {
    title: "Face Wash Fox — tech skincare in Vietnam",
    excerpt: "Face Wash Fox has become one of Vietnam’s tech skincare brands.",
    intro:
      "Beauty in the digital age is not only an essential need. It is also a way to live a modern lifestyle.",
    lead: "Face Wash Fox quickly made its mark in tech skincare, bringing guests a fresh, convenient experience.",
    cta: "Source: Phunu.nld.com.vn",
    texts: [
      "A clear place in the market",
      "As tech beauty becomes a market focus, Face Wash Fox has stepped forward with confidence. The brand keeps applying modern skincare technology, helping guests save time and raising the experience to a more professional level.",
      "In its facial washing bar stores, Face Wash Fox offers well-designed cleansing treatments, keeping guests comfortable and at ease in every small step.",
      "A skilled, experienced technician team and a modern equipment system are a major plus, helping the brand win trust from a wide range of guests — from young people who love skincare to busy office workers looking for a fast, still-effective solution.",
      "Beauty technology: the difference at the center",
      "Face Wash Fox’s appeal sits in constant renewal of technology in skincare. Instead of stopping at traditional methods, the brand uses modern deep-cleansing devices, combining Hydra Facial technology with other advanced treatment heads. These devices help remove dirt, excess oil, and dead skin effectively, while supplying the moisture skin needs to stay soft.",
      "Beyond cleansing, Face Wash Fox also focuses on in-depth care, such as needle-free, non-invasive infusion or Burnt Skin for sun-exposed skin — a common issue after beach trips or long hours outdoors. These treatments help soothe skin and support hydration, bringing back a smoother look.",
      "In 2025, as beauty trends focus on saving time for busy people, Face Wash Fox commits to modern skincare that is both fast and effective. The brand does not only meet a beauty need. It also aims to create a new lifestyle, where every guest feels confident and comfortable in their skin.",
    ],
    alts: [
      "Guests receiving skincare at Face Wash Fox",
      "A Face Wash Fox store space",
      "A skilled technician team and advanced equipment.",
      "High-tech facial machines at Face Wash Fox",
      "Guests experiencing an in-depth treatment at Face Wash Fox",
    ],
  },
  "mot-ngay-cua-anh-mat-vuong-tai-face-wash-fox": {
    title: "A day with Anh Mặt Vuông at Face Wash Fox",
    excerpt:
      "Viewers are used to seeing Duong Minh Tan on set. Few know that between packed shoot days, he is on a treatment bed at Face Wash Fox.",
    intro: "Not the first time. Not a trial to see how it feels.",
    lead: "It is a habit he kept from before he became brand ambassador.",
    cta: "Source: Tienphong.vn — Consultation hotline: 08898 66666 — Website: https://facewashfox.com",
    texts: [
      "A guest first — an ambassador later",
      "In March 2026, Face Wash Fox officially announced Duong Minh Tan — TikToker Anh Mặt Vuông, with more than 1.1 million followers — as brand ambassador for the year. For the people involved, this was not the start of a relationship — it was official recognition of something that was already there.",
      "He came to Face Wash Fox because he liked it — and stayed because he saw real results.",
      '"I was a FWF guest before I was an ambassador. My skin improved a lot," he said plainly.',
      "That is also why Face Wash Fox chose him. Not finding a fitting face and then convincing them to try. But realizing the person they needed was already there — walking into the store on his own, with no invitation.",
      '"We wanted someone who truly believes in what they are saying, and Anh Mặt Vuông is that person," a Face Wash Fox representative said about the partnership.',
      "A fast process — with real results",
      "Creators do not have much time. Shoots, meetings, travel — a long skincare session is something Duong Minh Tan cannot allow on a workday.",
      "That is exactly what he found at Face Wash Fox.",
      "Every visit starts with an AI skin scan — analyzing oil, hydration, and skin surface. Results are for reference and do not replace medical diagnosis. It only takes a few minutes, then the process is personalized from that result.",
      "Next come high-tech treatment steps — deep cleansing, extracting congestion, delivering actives with sonic waves, and locking in moisture with cold electrophoresis. Each step targets the issue the skin actually has — nothing extra, nothing skipped.",
      '"When I take care of my skin regularly at Face Wash Fox, my face changes a lot without taking much time. That is what I need," Anh Mặt Vuông said.',
      "What the camera cannot say — but the skin shows clearly",
      "Making video content means his face appears in front of millions of people every week. Under studio lights, after late nights, between a nonstop schedule — skin reflects everything the body is going through.",
      "Face Wash Fox does not promise magic. But with the right process, done regularly and personalized — the result is something he sees in the mirror each morning, with no one needing to say it.",
      '"Better skin means more confidence. And more confidence makes everything better — including standing in front of a camera," he said.',
      "As ambassador for 2026, Anh Mặt Vuông will join Face Wash Fox in communications and creative content — the same way he does everything: honestly, with no extra explanation needed.",
    ],
    alts: [
      "Anh Mặt Vuông was a FWF guest before becoming brand ambassador",
      "Signing ceremony announcing the FWF brand ambassador 2026",
      "AI skin scan and personalized process at Face Wash Fox",
      "Anh Mặt Vuông with Face Wash Fox",
    ],
  },
  "gift-voucher-da-sach-sau-rang-ro-ngay-tu-lan-dau": {
    title: "GIFT VOUCHER — DEEP-CLEAN SKIN, GLOWING FROM THE FIRST VISIT!",
    excerpt:
      "A gift voucher program with offers for guests who want to try a tech facial at Face Wash Fox.",
    intro:
      "Face Wash Fox brings a gift voucher program with offers for guests who want to try tech facial cleansing and skincare in store.",
    lead: "Offers apply under program conditions across the Face Wash Fox store network.",
    cta: "Hotline: 08898 66666",
    texts: [
      "Buy 1 get 1",
      "When using a service from VND 399,000, guests receive an extra Deep Clean tech facial session at Face Wash Fox.",
      "Stacked deals",
      "5% off combos or skincare services on listed prices when booking and using the service in store. 2% off when buying a Foxie card. Receive an Elravie Pro mini sample set when checking in at the store and tagging Face Wash Fox on Facebook.",
      "Conditions",
      "The program applies for the announced period. Vouchers cannot be exchanged for cash. Not valid with some other promotions or Aqua Peel. Please book ahead via hotline 08898 66666.",
    ],
    alts: [],
  },
};
